const data=[
    {
    id:1,
    Role: "Admin",
    access:{
      "home": 1,
      "trips": 1,
      "pastTrips": 1,
      "createTrip": 1,
      "alerts": 1,
      "alertManagement":1,
      "sensors": 1,
      "addSensors": 1,
      "routes" : 1,
      "addRoutes": 1,
      "users": 1,
      "addUsers":1,
      "dashBoard": 1,
      "report": 1,
      "roleSettings":1,
      }
    },
    {
        id:2,
    Role: "Driver",
    access:{
      "home": 1,
      "trips": 1,
      "pastTrips": 1,
      "createTrip": 1,
      "alerts": 1,
      "alertManagement":1,
      "sensors": 1,
      "addSensors": 1,
      "routes" : 1,
      "addRoutes": 1,
      "users": 1,
      "addUsers":1,
      "dashBoard": 1,
      "report": 1,
      "roleSettings":1,
      }
    },
    {
        id:3,
        Role: "FleetManager",
        access:{
          "home": 0,
          "trips": 1,
          "pastTrips": 0,
          "createTrip": 0,
          "alerts": 0,
          "alertManagement":0,
          "sensors": 0,
          "addSensors": 0,
          "routes" : 0,
          "addRoutes": 0,
          "users": 0,
          "addUsers":0,
          "dashBoard": 0,
          "report": 0   ,
          "roleSettings":0,
          }
        },
        // {
        //   Role: "SuperAdmin",
        //   access:{
        //     "home": 1,
        //     "trips": 1,
        //     "pastTrips": 1,
        //     "createTrip": 1,
        //     "alerts": 1,
        //     "alertManagement":1,
        //     "sensors": 1,
        //     "addSensors": 1,
        //     "routes" : 1,
        //     "addRoutes": 1,
        //     "users": 1,
        //     "addUsers":1,
        //     "dashBoard": 1,
        //     "report": 1,
        //     "roleSettings":1,
        //     }
        //   },
        //   {
        //     Role: "NewAdmin",
        //     access:{
        //       "home": 1,
        //       "trips": 1,
        //       "pastTrips": 1,
        //       "createTrip": 1,
        //       "alerts": 1,
        //       "alertManagement":1,
        //       "sensors": 1,
        //       "addSensors": 1,
        //       "routes" : 1,
        //       "addRoutes": 1,
        //       "users": 1,
        //       "addUsers":1,
        //       "dashBoard": 1,
        //       "report": 1,
        //       "roleSettings":1,
        //       }
        //     },
            
  ]
  export default data;